site_name: ugo_py_doc
site_url: http://ugo-py-doc.readthedocs.io/en/latest/
repo_url: https://github.com/ugoproto/ugo_py_doc
site_description: A Python documentation website.
site_author: Ugo Spark
site_favicon: faviconfire.ico
copyright: null
#google_analytics: ['UA-36723568-3', 'mkdocs.org']
remote_branch: master
remote_name: ugo_py_doc
pages:
    - Home: 'index.md'
    - Apprenez à programmer en Python: 'Apprenez a programmer en Python.md'
    - Automate the Boring Stuff with Python: 'Automate the Boring Stuff with Python.md'
    - Codecademy Python: 'Codecademy Python.md'
    - DataCamp Importing Data into Python 3: 'DataCamp Importing Data into Python 3.md'
    - DataCamp Python 3 for Data Science: 'DataCamp Python 3 for Data Science.md'
    - Decorators: 'Decorators.md'
    - Introduction to Python: 'Introduction to Python.md'
    - IPython Notebook, Collection: 'IPython Notebook.md'
    - Learn Python the Hard Way: 'Learn Python the Hard Way.md'
    - Managing Your Biological Data with Python: 'Managing Your Biological Data with Python.md'
    - Python Code Snippets: 'Python Code Snippets.md'
    - Python for Education: 'Python for Education.md'
    - Scientific Python (Scipy Stack): 'Scientific Python (Scipy Stack).md'
    
theme: readthedocs
# Other themes:
    # readthedocs
    # mkdocs

# Build PDF & ePub
formats: 
    - pdf
    - epub
    
# Math equations:
    # extra JS (see below)
    # extra Python (see below)
    # new extension (see below)
# Required to load the MathJax javascript for the mdx_math.py
# https://github.com/mkdocs/mkdocs/issues/253

# Python
python:
    version: 2 # for unicode
    setup_py_install: true

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True # for use of inline $..$
    - wikilinks # internal links with [[bracketed]]
    - smarty # additional characters
#    - subscript
#    - superscript
    - nl2br # new line to break
    - toc:
        title: Content
        permalink: True
        baselevel: 3

# Required to load the MathJax javascript for the mdx_math.py        
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','mathjaxhelper.js']