site_name: ugo_py_doc
site_url: https://ugoproto.github.io/ugo_py_doc/
#repo_url: https://github.com/ugoproto/ugo_py_doc
site_description: A Python documentation website.
site_author: Ugo Sparks
#site_favicon: favicon.ico
copyright: © Ugo Sparks
google_analytics: 
    - 'UA-93008985-2'
    - 'auto'
#remote_branch: master
#remote_name: ugo_py_doc

pages:
    - Home: 'index.md'
    - Basics & More:
        - Python Cheat Sheets: 'Py_CS.md'
        - Python Preliminaries: 'Python_Preliminaries.md'
        - Python Nice to Have: 'Python_Nice_to_Have.md'
        - Freeze the Code: 'Freeze_the_Code.md'
        - Decorators: 'Decorators.md'
        - Write Better Python with PEP: 'Write_Better_Python.md'
        - Regular Expressions (REGEX): 'Regex.md'
        - Databases: 'Databases.md'
        - Datetime: 'Datetime.md'
        - Execute Highlighted Python Code in gedit: 'Execute_Highlighted_Python_Code_in_gedit.md'
    - SciPy Stack: 
        - Scipy Stack Cheat Sheets: 'Scipy_CS.md'
        - Jupyter Notebook Cheat Sheets: 'JN_CS.md'        
        - Scientific Python (the SciPy Stack): 'Scientific Python (the SciPy Stack).md'
        - Importing Data into Python: 'Importing Data into Python.md'
        - Python for Data Science: 'Python for Data Science.md'
        - Tidy Data in Python: 'Tidy_Data_in_Python.md'
        - Lists: 'Lists.md'
        - IPython Notebook, Collection: 'IPython Notebook.md'
        - Python Numpy Arrays: 'Python Numpy Arrays.md'
        - Vectors and Arrays (Linear Algebra): 'Vectors and Arrays (Linear Algebra).md'
        - Matplotlib, Python Plotting: 'Matplotlib, Python Plotting.md'
        - Viewing 3D Volumetric Data With Matplotlib: 'Viewing+3D+Volumetric+Data+With+Matplotlib.md'
        - Seaborn, Python's Statistical Data Visualization Library: 'Seaborn, Python Statistical Data Visualization Library.md'
        - Pandas DataFrames: 'Pandas+DataFrames.md'
        - Write Idiomatic Pandas Code: 'Write Idiomatic Pandas Code.md'
        - Exploratory Data Analysis: 'Exploratory Data Analysis.md'
        - Intro to data.world in Python: 'Intro to data.world in Python.md'
        - Python and Excel: 'Python+And+Excel.md'
        - Overview of scikit-learn: 'Overview_of_scikit-learn.md'
        - k-NN, Linear regression, Logit, Scaling, Centering, Noise: 'k-NN_Linear_regression_Logit_Scaling_Centering_Noise.md'
        - Time Series Analysis: 'Time_Series_Analysis.md'
        - Sentiment Analysis with Twitter: 'Sentiment_Analysis_with_Twitter.md'
        - EDA, Machine Learning, Feature Engineering, and Kaggle: 'EDA_Machine_Learning_Feature_Engineering_and_Kaggle.md'
    - Courses:
        - Apprenez à programmer en Python: 'Apprenez a programmer en Python.md'
        - Codecademy Python: 'Codecademy Python.md'
        - Learn Python the Hard Way: 'Learn Python the Hard Way.md'
        - Python Code Snippets: 'Python Code Snippets.md'
        - Introduction to Python: 'Introduction to Python.md'
    - Manuals:
        - Automate the Boring Stuff with Python: 'Automate the Boring Stuff with Python.md'
        - Real Python: 'Real_Python.md'
        - Managing Your Biological Data with Python: 'Managing Your Biological Data with Python.md'
        - Python for Education: 'Python for Education.md'
 
theme: readthedocs
# Other themes:
    # readthedocs
    # mkdocs

# Build PDF & ePub (only on Readthedocs)
#formats: 
#    - pdf

# Interlinks
# [link](to_other_page.md)
# [link](../relative/page.md)
    
# Python
python:
    version: 2 # for unicode
    setup_py_install: True

# Math equations:
# extra JS (see below)
# extra Python (see below)
# new extension (see below)
# Required to load the MathJax javascript for the mdx_math.py
# https://github.com/mkdocs/mkdocs/issues/253

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True # for use of inline $..$
    - wikilinks # internal links with [[bracketed]]
    - smarty # additional characters
    - subscript
    - superscript
    - nl2br # need a new line to break
    - toc:
        title: CONTENT
        permalink: True
        baselevel: 3
    - footnotes

# Required to load the MathJax javascript for the mdx_math.py        
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','mathjaxhelper.js']
