site_name: ugo_py_doc
site_url: https://ugoproto.github.io/ugo_py_doc/
#repo_url: https://github.com/ugoproto/ugo_py_doc
site_description: A Python documentation website.
site_author: Ugo Spark
#site_favicon: favicon.ico
copyright: © Ugo Spark
#google_analytics: ['UA-36723568-3', 'mkdocs.org']
#remote_branch: master
#remote_name: ugo_py_doc

pages:
    - Home: 'index.md'
    - Basics & More:
        - Python Preliminaries: 'Python_Preliminaries.md'
        - Python Nice to Have: 'Python_Nice_to_Have.md'
        - Freeze the Code: 'Freeze_the_Code.md'
        - Decorators: 'Decorators.md'
        - Write Better Python with PEP: 'Write_Better_Python.md'
        - Regular Expressions (REGEX): 'Regex.md'
        - Databases: 'Databases.md'
        - Datetime: 'Datetime.md'
    - SciPy Stack:
        - Scientific Python (the SciPy Stack): 'Scientific Python (the SciPy Stack).md'
        - DataCamp Importing Data into Python 3: 'DataCamp Importing Data into Python 3.md'
        - DataCamp Python 3 for Data Science: 'DataCamp Python 3 for Data Science.md'
        - Tidy Data in Python: 'Tidy_Data_in_Python.md'
        - IPython Notebook, Collection: 'IPython Notebook.md'
    - Courses:
        - Apprenez à programmer en Python: 'Apprenez a programmer en Python.md'
        - Codecademy Python: 'Codecademy Python.md'
        - Learn Python the Hard Way: 'Learn Python the Hard Way.md'
        - Python Code Snippets: 'Python Code Snippets.md'
        - Introduction to Python: 'Introduction to Python.md'
    - Manuals:
        - Automate the Boring Stuff with Python: 'Automate the Boring Stuff with Python.md'
        - Managing Your Biological Data with Python: 'Managing Your Biological Data with Python.md'
        - Python for Education: 'Python for Education.md'
 
theme: readthedocs
# Other themes:
    # readthedocs
    # mkdocs

# Build PDF & ePub (only on Readthedocs)
#formats: 
#    - pdf

# Interlinks
# [link](to_other_page.md)
# [link](../relative/page.md)
    
# Python
python:
    version: 2 # for unicode
    setup_py_install: True

# Math equations:
# extra JS (see below)
# extra Python (see below)
# new extension (see below)
# Required to load the MathJax javascript for the mdx_math.py
# https://github.com/mkdocs/mkdocs/issues/253

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True # for use of inline $..$
    - wikilinks # internal links with [[bracketed]]
    - smarty # additional characters
    - subscript
    - superscript
    - nl2br # need a new line to break
    - toc:
        title: CONTENT
        permalink: True
        baselevel: 3
    - footnotes

# Required to load the MathJax javascript for the mdx_math.py        
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','mathjaxhelper.js']